### ISSUE TITLE
Can't build on ubuntu 22.04

### ISSUE THREAD

**Issue by leodumont** [pop-os/shell#1695]
Compilation on ubuntu 22.04 failed

make local-install returned following error :

```
tsconfig.json:19:19 - error TS4124: Compiler option 'module' of value 'nodenext' is unstable. Use nightly TypeScript to silence this error. Try updating with 'npm install -D typescript@next'.

19         "module": "NodeNext"
                     ~~~~~~~~~~

Found 1 error.
```
TipeScript version : 
```
tsc -v
Version 4.5.4
```

npm version : 
```
npm -v
10.2.4
```

**Comment by mmstick** [comment]
You have a node installation in your home folder probably. You can't build this if any parent directory has node installed.

**Comment by leodumont** [comment]
Thanks for your help.

If i'm not mistaken, I don't have a node install in home directory :

```
which -a node
/usr/bin/node
/bin/node
```

**Comment by leodumont** [comment]
I finally get what was wong : forgot to checkout to the jammy branche after git clone...
If anyone needs it :
```
git clone https://github.com/pop-os/shell.git
cd shell
git checkout master_jammy
make local-install
```

**Comment by tmeijn** [comment]
> I finally get what was wong : forgot to checkout to the jammy branche after git clone... If anyone needs it :
> 
> ```
> git clone https://github.com/pop-os/shell.git
> cd shell
> git checkout master_jammy
> make local-install
> ```

You can also do `git clone https://github.com/pop-os/shell.git --branch master_jammy`

**Comment by logoff** [comment]
I think this should be properly documented in https://support.system76.com/articles/pop-shell/.

**Comment by jacobgkau** [comment]
@logoff I've opened a PR to include the branch information in that support article here: https://github.com/system76/docs/pull/1252
