### ISSUE TITLE
Build fail (Arch)

### ISSUE THREAD

**Issue by gobborg** [pop-os/shell#1341]
**(1) Issue/Bug Description:**
error making: gnome-shell-extension-pop-shell
When attempting to install the shell, everything worked until the build. The error is ```src/settings.ts:25:24 - error TS2345: Argument of type 'unknown is not assignable to parameter of type 'string'.```
``` 25    global.log(err)```.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/81018718/151645598-20218bee-5092-4eef-b4d5-07bfb41bc193.png)

**(2) Steps to reproduce (if you know):**
Try to install via ```yay -S gnome-shell-extension-pop-shell``` and choose default installation options.

**(3) Expected behavior:**
Successful build

**(4) Distribution (run `cat /etc/os-release`):**
 Arch Linux

**(5) Gnome Shell version:**
41.2 (Yes, I know this is not 3.36.)

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
```aur/gnome-shell-extension-pop-shell-bin 1.2.0-4```

**(7) Where was Pop Shell installed from:**
```yay -S gnome-shell-extension-pop-shell```

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
Primary Horizontal 16:9

**(9) Other Installed/Enabled Extensions:**
```aur/pop-shell-shortcuts-git 1:r30.52cc83f-2 ```

**(10) Other Notes:**
I was able to install and build with the precompiled ```yay -S gnome-shell-extension-pop-shell-bin```.

**Comment by 0n0w1c** [comment]
I ran into the same compile error attempting to build it from the AUR for aarch64.

**Comment by 0n0w1c** [comment]
The -git package in the AUR builds properly, and it builds for aarch64 too.

**Comment by kn0wmad** [comment]
Same error building from AUR, aarch64, Gnome 41.3.  I know this is not listed as a supported version, but was hoping to give this a try.

**Comment by colbymorrison** [comment]
`yay -S gnome-shell-extension-pop-shell-git` worked for me. GNOME 41.3.

**Comment by CharlieBra7o** [comment]
**System:**
- x86_64
- gnome 41.3

I am having trouble building gnome-shell-extension-pop-shell-git for over a month now (stripped down to the essential kinds of errors):
`src/extension.ts:30:15 - error TS2305: Module '"events"' has no exported member 'ExtEvent'.`
`src/extension.ts:46:9 - error TS2339: Property 'GlobalEvent' does not exist on type 'typeof EventEmitter'.`
`../../../../../node_modules/@types/node/globals.global.d.ts:1:13 - error TS2451: Cannot redeclare block-scoped variable 'global'.`
`../../../../../node_modules/@types/node/timers.d.ts:22:35 - error TS2339: Property 'setTimeout' does not exist on type 'Global'.`

Considering @colbymorrison is able to build successfully:
Might this be an issue with node somehow? Maybe the (module) version dependencies are not resolved correctly or something... It looks to me as if my node version is somehow newer, thus now throws errors of incorrect/incompatible "old" code... Unfortunately, I have no expertise when it comes to node, so my guess could be completely wrong...

**Comment by jixbo** [comment]
I was facing the same issue as @CharlieBra7o.
There was a node_modules in my home folder, which was being used for the install.
Deleting the node_modules folder `rm ~/node_modules/` fixed the issue for me using ubuntu 22.04.

BTW I had to build jammy_master branch, to get the extension to work in ubuntu 22.04

**Comment by cephbo** [comment]
@jixbo : Thank you for the tip with the user node_modules directory! After removing/renaming it I was also able to build master_jammy for gnome-shell 42.0-1. As far as I can see everything is working perfectly!

**Comment by picnoir** [comment]
Same error on NixOS here on the latest release here.

It seems like it has been fixed on master by 8be10fa999b6631382c4f71826ee78ea9993f4.

This commit is not included in the latest release. It might make sense to either backport it, either cutting a new release containing it.

**Comment by chatodux** [comment]
I'm facing the same issue, in my case using **RHEL 9.1**. **Typescript** version **4.8.4**. 

![gitgud](https://user-images.githubusercontent.com/109466911/205815469-fcc10360-835b-44c3-9b1d-00d54823d101.png)
