### ISSUE TITLE
Activities overview broken on 20.04 LTS (3.36) with Pop Shell

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/shell#1082]
**(1) Issue/Bug Description:** When attempting to access the Activities overview on a 20.04 LTS machine (GNOME 3.36), no windows are shown and I cannot exit Activities:

![Screenshot from 2021-07-13 11-14-11](https://user-images.githubusercontent.com/7199422/125496634-65ccd24d-88b6-4207-b7b1-aaec2cab0829.png)

I'm able to recover by restarting GNOME Shell. I get the following error in the logs:

```
Jul 13 11:13:40 pop-os gnome-shell[2512]: JS ERROR: TypeError: meta_window.get_wm_class is not a function
                                          skiptaskbar_shall_hide@/usr/share/gnome-shell/extensions/pop-shell@system76.com/config.js:85:35
                                          _show_skip_taskbar_windows/Workspace.prototype._isOverviewWindow@/usr/share/gnome-shell/extensions/pop-shell@system76.com/extension.js:2002:36
                                          _init@resource:///org/gnome/shell/ui/workspace.js:1173:22
                                          _updateWorkspaces@resource:///org/gnome/shell/ui/workspacesView.js:232:29
                                          _init@resource:///org/gnome/shell/ui/workspacesView.js:91:14
                                          _updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:682:24
                                          show@resource:///org/gnome/shell/ui/workspacesView.js:612:14
                                          show@resource:///org/gnome/shell/ui/viewSelector.js:276:33
                                          _animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27
                                          show@resource:///org/gnome/shell/ui/overview.js:566:14
                                          toggle@resource:///org/gnome/shell/ui/overview.js:689:18
                                          vfunc_event@resource:///org/gnome/shell/ui/panel.js:482:31
```

Based on the error message, I believe this is caused by https://github.com/pop-os/shell/pull/1069/commits/dc0e306962064b93f00cc55a50ba9901971c4c92, the final commit in https://github.com/pop-os/shell/pull/1069 that was not tested before merging (branch protection rules have since been added to prevent this from occurring again.)

**(2) Steps to reproduce (if you know):** Install the master branch of Pop Shell on a Pop!_OS 20.04 LTS system and open the Activities menu.

**(3) Expected behavior:** The Activities menu should function.

**(4) Distribution (run `cat /etc/os-release`):** Pop!_OS 20.04 LTS

**(5) Gnome Shell version:** 3.36

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**
- f4894c8 (master)
- 304cafd (default-methods)

**(7) Where was Pop Shell installed from:** Proposed PPA, staging repos.

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):** 1080p internal + 1440p external.

**(9) Other Installed/Enabled Extensions:** Pop!_OS defaults only.

**(10) Other Notes:** N/A

**Comment by jacobgkau** [comment]
I thought this might be what people in https://github.com/pop-os/shell/issues/1072 are experiencing on Ubuntu LTS, but the logs look different. None of their logs mention `meta_window.get_wm_class`.

**Comment by Scarzer** [comment]
I just rechecked my logs updated my comment in #1072 . I'm also seeing a `meta_window.get_wm_class` error

**Comment by jacobgkau** [comment]
> I just rechecked my logs updated my comment in #1072 . I'm also seeing a `meta_window.get_wm_class` error

Thank you, that would have been nice to know. I'm closing this as a duplicate of https://github.com/pop-os/shell/issues/1072, I'm not seeing the recursion errors it's referring to but I do see the Activities menu issue on Ubuntu and Pop!_OS.
