### ISSUE TITLE
Activate launcher [Super + /] does not work on Gnome 40.4 - Ubuntu 21.10

### ISSUE THREAD

**Issue by jixbo** [pop-os/shell#1190]
Activate launcher [Super + /] does not work, using the latest commit on master branch [5220303](https://github.com/pop-os/shell/commit/522030336565badc6fd6068bd5e38328996aa4bf)

Using Ubuntu 21.10, which ships with Gnome 40.4.

Primary monitor, 3440x1440 (21:9), and below using laptop's integrated screen 1920x1080 (16:9), vertical arrangement.

Other installed extensions:
Brightness control using ddcutil
Clipboard Indicator
GSConnect
Night Theme Switcher
OpenWeather
Unite
Vitals

Tried disabling all of them but it didn't help.

`journalctl /usr/bin/gnome-shell -f` shows the following when trying to use the shortcut:

```Sep 27 13:16:18 thinkpad gnome-shell[37532]: pop-shell:  [WARN] pop-shell: deprecated function called (dialog_launcher::load_desktop_files)
Sep 27 13:16:18 thinkpad gnome-shell[37532]: pop-shell: [DEBUG] starting pop-launcher service
Sep 27 13:16:18 thinkpad gnome-shell[37532]: JS ERROR: TypeError: log.error is not a function
                                             async_process_ipc@/home/jixbo/.local/share/gnome-shell/extensions/pop-shell@system76.com/utils.js:97:13
                                             start_services@/home/jixbo/.local/share/gnome-shell/extensions/pop-shell@system76.com/launcher.js:285:31
                                             open@/home/jixbo/.local/share/gnome-shell/extensions/pop-shell@system76.com/launcher.js:275:14
                                             activate-launcher@/home/jixbo/.local/share/gnome-shell/extensions/pop-shell@system76.com/keybindings.js:11:35
```

Thanks.

**Comment by mmstick** [comment]
Did you install https://github.com/pop-os/launcher/?

**Comment by jixbo** [comment]
No, didn't realize it's a dependency now.
How do I install it? Make throws an error:
```$ make
cargo build -p pop-launcher-bin --release
error: failed to get `smol` as a dependency of package `pop-launcher-bin v1.0.0 (/home/jixbo/Downloads/launcher-1.0.1/bin)`

Caused by:
  failed to load source for dependency `smol`

Caused by:
  Unable to update registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to update replaced source registry `https://github.com/rust-lang/crates.io-index`

Caused by:
  failed to read root of directory source: /home/jixbo/Downloads/launcher-1.0.1/vendor

Caused by:
  No such file or directory (os error 2)
make: *** [Makefile:33: all] Error 101
```

**Comment by mmstick** [comment]
It looks like you're installing from the tarball, which requires that you use vendor flags to build with the bundled vendored dependencies.

**Comment by jixbo** [comment]
True, tried to use the tarball as the install procedure isn't documented in the repo.
Managed to install it with `make` and `make install` using the repo, and the issue is fixed now.

But I'm left with a bittersweet taste, as I feel like this dependency should be better documented and warned of during installation, and there are not clear instructions in the readme of https://github.com/pop-os/launcher/ of how to install.

Thanks.
